version: "3.0"

services:
  db:
    container_name: "monoero-node-explorer-db"
    hostname: postgres
    image: postgres:latest
    command: postgres -c stats_temp_directory=/tmp
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=node
      - POSTGRES_USER=node
      - POSTGRES_PASSWORD=node
    ports:
      - 5432:5432
      
  pgadmin:
    container_name: "monoero-node-explorer-pgadmin"
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@node.live
      PGADMIN_DEFAULT_PASSWORD: node
    restart: unless-stopped

  frontend:
    container_name: "monoero-node-explorer-frontend"
    build: ./client
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start
